import operator
from typing import Annotated, List, TypedDict

# defining the state of our agent
# this dict holds data moving between nodes
class AgentState(TypedDict):
    # original question from user
    question: str
    
    # list of docs found... using operator.add to append new docs 
    # instead of overwriting old ones
    documents: Annotated[List[str], operator.add]
    
    # final answer generated by llm
    generation: str